chore(workflow): run bot until complete
userbotindo/Anjani pull request #250
Opened 2023-03-04 17:07 UTC by MrMissx

- run bot until complete
- add PyPI publish jobs

2023-03-05 13:17 UTC, adekmaulana requested changes

2023-03-05 13:17 UTC, adekmaulana commented on anjani/core/telegram_bot.py
> +        ci = os.getenv("IS_CI")
Mending taro di config ga sih? ini

2023-03-05 13:25 UTC, MrMissx commented on anjani/core/telegram_bot.py
> +        ci = os.getenv("IS_CI")
cuma dipake 1x mau ditaruh?

2023-03-05 15:20 UTC, adekmaulana commented on anjani/core/telegram_bot.py
> +        ci = os.getenv("IS_CI")
> cuma dipake 1x mau ditaruh?

gapapa dr pada di situ keliatan jelek

2023-03-10 07:49 UTC, adekmaulana approved these changes

2023-03-10 07:50 UTC, merged